package queryclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2019-06-19T22:29:52.556+08:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://services.cnotf.yss.com", name = "queryServiceWS")
@XmlSeeAlso({ObjectFactory.class})
public interface QueryServiceWS {

    @WebMethod
    @RequestWrapper(localName = "queryTrusteeFeeData", targetNamespace = "http://services.cnotf.yss.com", className = "com.yss.cnotf.services.QueryTrusteeFeeData")
    @ResponseWrapper(localName = "queryTrusteeFeeDataResponse", targetNamespace = "http://services.cnotf.yss.com", className = "com.yss.cnotf.services.QueryTrusteeFeeDataResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<TrusteeFeeInfo> queryTrusteeFeeData(
            @WebParam(name = "arg0", targetNamespace = "")
                    TrusteeFeeInfo arg0
    );
}
