package saveclient;

import queryclient.TrusteeFeeInfo;

import javax.jws.*;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2019-07-09T10:49:50.107+08:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://services.cnotf.yss.com", name = "saveWebServiceWS")
@XmlSeeAlso({ObjectFactory.class})
public interface SaveWebServiceWS {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveTrusteeFeeData", targetNamespace = "http://services.cnotf.yss.com", className = "com.yss.cnotf.services.SaveTrusteeFeeData")
    @WebMethod
    @ResponseWrapper(localName = "saveTrusteeFeeDataResponse", targetNamespace = "http://services.cnotf.yss.com", className = "com.yss.cnotf.services.SaveTrusteeFeeDataResponse")
    public String saveTrusteeFeeData(
            @WebParam(name = "arg0", targetNamespace = "")
                    java.util.List<TrusteeFeeInfo> arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveHandDate", targetNamespace = "http://services.cnotf.yss.com", className = "com.yss.cnotf.services.SaveHandDate")
    @WebMethod
    @ResponseWrapper(localName = "saveHandDateResponse", targetNamespace = "http://services.cnotf.yss.com", className = "com.yss.cnotf.services.SaveHandDateResponse")
    public String saveHandDate(
            @WebParam(name = "arg0", targetNamespace = "")
                    java.util.List<HandDateInfo> arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveBiDate", targetNamespace = "http://services.cnotf.yss.com", className = "com.yss.cnotf.services.SaveBiDate")
    @WebMethod
    @ResponseWrapper(localName = "saveBiDateResponse", targetNamespace = "http://services.cnotf.yss.com", className = "com.yss.cnotf.services.SaveBiDateResponse")
    public String saveBiDate(
            @WebParam(name = "arg0", targetNamespace = "")
                    BiDateInfo arg0
    );
}
