package saveclient;

import util.PropertiesUtil;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2019-06-18T17:40:46.736+08:00
 * Generated source version: 3.1.8
 * 
 */
@WebServiceClient(name = "YssWebServiceIService", 
                  wsdlLocation = "http://localhost:8003/yss_save_service?wsdl",
                  targetNamespace = "http://services.cnotf.yss.com") 
public class YssWebServiceIService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services.cnotf.yss.com", "YssWebServiceIService");
    public final static QName SaveWebServiceWSPort = new QName("http://services.cnotf.yss.com", "saveWebServiceWSPort");
    static {
        URL url = null;
        PropertiesUtil propertiesUtil = new PropertiesUtil("properties/ipport.properties");
        String address = propertiesUtil.readProperty("saveaddress");
        try {
            url = new URL(address);
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(YssWebServiceIService.class.getName())
                    .log(java.util.logging.Level.INFO,
                            "Can not initialize the default wsdl from {0}", address);
        }
        WSDL_LOCATION = url;
    }

    public YssWebServiceIService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public YssWebServiceIService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public YssWebServiceIService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public YssWebServiceIService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public YssWebServiceIService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public YssWebServiceIService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns SaveWebServiceWS
     */
    @WebEndpoint(name = "saveWebServiceWSPort")
    public SaveWebServiceWS getSaveWebServiceWSPort() {
        return super.getPort(SaveWebServiceWSPort, SaveWebServiceWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SaveWebServiceWS
     */
    @WebEndpoint(name = "saveWebServiceWSPort")
    public SaveWebServiceWS getSaveWebServiceWSPort(WebServiceFeature... features) {
        return super.getPort(SaveWebServiceWSPort, SaveWebServiceWS.class, features);
    }

}
