package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2019-05-13T16:20:19.356+08:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://com.yss.hello.service", name = "yssWebServiceWS")
@XmlSeeAlso({ObjectFactory.class})
public interface YssWebServiceWS {

    @WebMethod
    @RequestWrapper(localName = "getHandDate", targetNamespace = "http://com.yss.hello.service", className = "service.hello.yss.com.GetHandDate")
    @ResponseWrapper(localName = "getHandDateResponse", targetNamespace = "http://com.yss.hello.service", className = "service.hello.yss.com.GetHandDateResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getHandDate(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "getBiDate", targetNamespace = "http://com.yss.hello.service", className = "service.hello.yss.com.GetBiDate")
    @ResponseWrapper(localName = "getBiDateResponse", targetNamespace = "http://com.yss.hello.service", className = "service.hello.yss.com.GetBiDateResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getBiDate(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    String arg3
    );
}
