package client;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2019-05-24T17:40:41.123+08:00
 * Generated source version: 3.1.8
 * 
 */
@WebServiceClient(name = "yssWebServiceIService", 
                  wsdlLocation = "http://192.168.0.107:8002/yss_web_service?wsdl",
                  targetNamespace = "http://com.yss.hello.service") 
public class YssWebServiceIService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://com.yss.hello.service", "yssWebServiceIService");
    public final static QName YssWebServiceWSPort = new QName("http://com.yss.hello.service", "yssWebServiceWSPort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.0.107:8002/yss_web_service?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(YssWebServiceIService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.0.107:8002/yss_web_service?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public YssWebServiceIService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public YssWebServiceIService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public YssWebServiceIService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public YssWebServiceIService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public YssWebServiceIService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public YssWebServiceIService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns YssWebServiceWS
     */
    @WebEndpoint(name = "yssWebServiceWSPort")
    public YssWebServiceWS getYssWebServiceWSPort() {
        return super.getPort(YssWebServiceWSPort, YssWebServiceWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns YssWebServiceWS
     */
    @WebEndpoint(name = "yssWebServiceWSPort")
    public YssWebServiceWS getYssWebServiceWSPort(WebServiceFeature... features) {
        return super.getPort(YssWebServiceWSPort, YssWebServiceWS.class, features);
    }

}
